# Generated by Django 3.2.6 on 2021-08-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='displayname',
            new_name='roomname',
        ),
        migrations.RemoveField(
            model_name='message',
            name='savename',
        ),
    ]
